
package webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param accountNumber
     * @return
     *     returns webservice.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://webService/", className = "webservice.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://webService/", className = "webservice.GetAccountResponse")
    @Action(input = "http://webService/BanqueService/getAccountRequest", output = "http://webService/BanqueService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "accountNumber", targetNamespace = "")
        int accountNumber);

    /**
     * 
     * @return
     *     returns java.util.List<webservice.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "accountList", targetNamespace = "http://webService/", className = "webservice.AccountList")
    @ResponseWrapper(localName = "accountListResponse", targetNamespace = "http://webService/", className = "webservice.AccountListResponse")
    @Action(input = "http://webService/BanqueService/accountListRequest", output = "http://webService/BanqueService/accountListResponse")
    public List<Account> accountList();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuro-TND")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuro-TND", targetNamespace = "http://webService/", className = "webservice.ConversionEuroTND")
    @ResponseWrapper(localName = "ConversionEuro-TNDResponse", targetNamespace = "http://webService/", className = "webservice.ConversionEuroTNDResponse")
    @Action(input = "http://webService/BanqueService/ConversionEuro-TNDRequest", output = "http://webService/BanqueService/ConversionEuro-TNDResponse")
    public double conversionEuroTND(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
