//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService/", ConfigurationName="ServiceReference1.BanqueService")]
    public interface BanqueService {
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ConversionEuro-TND) du message ConversionEuro-TNDRequest ne correspond pas à la valeur par défaut (ConversionEuroTND)
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/BanqueService/ConversionEuro-TNDRequest", ReplyAction="http://webService/BanqueService/ConversionEuro-TNDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApp1.ServiceReference1.ConversionEuroTNDResponse ConversionEuroTND(ConsoleApp1.ServiceReference1.ConversionEuroTNDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/BanqueService/ConversionEuro-TNDRequest", ReplyAction="http://webService/BanqueService/ConversionEuro-TNDResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.ConversionEuroTNDResponse> ConversionEuroTNDAsync(ConsoleApp1.ServiceReference1.ConversionEuroTNDRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/BanqueService/getAccountRequest", ReplyAction="http://webService/BanqueService/getAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApp1.ServiceReference1.getAccountResponse getAccount(ConsoleApp1.ServiceReference1.getAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/BanqueService/getAccountRequest", ReplyAction="http://webService/BanqueService/getAccountResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.getAccountResponse> getAccountAsync(ConsoleApp1.ServiceReference1.getAccountRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/BanqueService/accountListRequest", ReplyAction="http://webService/BanqueService/accountListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApp1.ServiceReference1.accountListResponse accountList(ConsoleApp1.ServiceReference1.accountListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/BanqueService/accountListRequest", ReplyAction="http://webService/BanqueService/accountListResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.accountListResponse> accountListAsync(ConsoleApp1.ServiceReference1.accountListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEuro-TND", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class ConversionEuroTNDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double montant;
        
        public ConversionEuroTNDRequest() {
        }
        
        public ConversionEuroTNDRequest(double montant) {
            this.montant = montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEuro-TNDResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class ConversionEuroTNDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public ConversionEuroTNDResponse() {
        }
        
        public ConversionEuroTNDResponse(double @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService/")]
    public partial class account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int accountNbrField;
        
        private double soldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int accountNbr {
            get {
                return this.accountNbrField;
            }
            set {
                this.accountNbrField = value;
                this.RaisePropertyChanged("accountNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double sold {
            get {
                return this.soldField;
            }
            set {
                this.soldField = value;
                this.RaisePropertyChanged("sold");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccount", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class getAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int accountNumber;
        
        public getAccountRequest() {
        }
        
        public getAccountRequest(int accountNumber) {
            this.accountNumber = accountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class getAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApp1.ServiceReference1.account @return;
        
        public getAccountResponse() {
        }
        
        public getAccountResponse(ConsoleApp1.ServiceReference1.account @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="accountList", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class accountListRequest {
        
        public accountListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="accountListResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class accountListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApp1.ServiceReference1.account[] @return;
        
        public accountListResponse() {
        }
        
        public accountListResponse(ConsoleApp1.ServiceReference1.account[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BanqueServiceChannel : ConsoleApp1.ServiceReference1.BanqueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanqueServiceClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.BanqueService>, ConsoleApp1.ServiceReference1.BanqueService {
        
        public BanqueServiceClient() {
        }
        
        public BanqueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanqueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.ConversionEuroTNDResponse ConsoleApp1.ServiceReference1.BanqueService.ConversionEuroTND(ConsoleApp1.ServiceReference1.ConversionEuroTNDRequest request) {
            return base.Channel.ConversionEuroTND(request);
        }
        
        public double ConversionEuroTND(double montant) {
            ConsoleApp1.ServiceReference1.ConversionEuroTNDRequest inValue = new ConsoleApp1.ServiceReference1.ConversionEuroTNDRequest();
            inValue.montant = montant;
            ConsoleApp1.ServiceReference1.ConversionEuroTNDResponse retVal = ((ConsoleApp1.ServiceReference1.BanqueService)(this)).ConversionEuroTND(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.ConversionEuroTNDResponse> ConsoleApp1.ServiceReference1.BanqueService.ConversionEuroTNDAsync(ConsoleApp1.ServiceReference1.ConversionEuroTNDRequest request) {
            return base.Channel.ConversionEuroTNDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.ConversionEuroTNDResponse> ConversionEuroTNDAsync(double montant) {
            ConsoleApp1.ServiceReference1.ConversionEuroTNDRequest inValue = new ConsoleApp1.ServiceReference1.ConversionEuroTNDRequest();
            inValue.montant = montant;
            return ((ConsoleApp1.ServiceReference1.BanqueService)(this)).ConversionEuroTNDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.getAccountResponse ConsoleApp1.ServiceReference1.BanqueService.getAccount(ConsoleApp1.ServiceReference1.getAccountRequest request) {
            return base.Channel.getAccount(request);
        }
        
        public ConsoleApp1.ServiceReference1.account getAccount(int accountNumber) {
            ConsoleApp1.ServiceReference1.getAccountRequest inValue = new ConsoleApp1.ServiceReference1.getAccountRequest();
            inValue.accountNumber = accountNumber;
            ConsoleApp1.ServiceReference1.getAccountResponse retVal = ((ConsoleApp1.ServiceReference1.BanqueService)(this)).getAccount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.getAccountResponse> ConsoleApp1.ServiceReference1.BanqueService.getAccountAsync(ConsoleApp1.ServiceReference1.getAccountRequest request) {
            return base.Channel.getAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.getAccountResponse> getAccountAsync(int accountNumber) {
            ConsoleApp1.ServiceReference1.getAccountRequest inValue = new ConsoleApp1.ServiceReference1.getAccountRequest();
            inValue.accountNumber = accountNumber;
            return ((ConsoleApp1.ServiceReference1.BanqueService)(this)).getAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.accountListResponse ConsoleApp1.ServiceReference1.BanqueService.accountList(ConsoleApp1.ServiceReference1.accountListRequest request) {
            return base.Channel.accountList(request);
        }
        
        public ConsoleApp1.ServiceReference1.account[] accountList() {
            ConsoleApp1.ServiceReference1.accountListRequest inValue = new ConsoleApp1.ServiceReference1.accountListRequest();
            ConsoleApp1.ServiceReference1.accountListResponse retVal = ((ConsoleApp1.ServiceReference1.BanqueService)(this)).accountList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.accountListResponse> ConsoleApp1.ServiceReference1.BanqueService.accountListAsync(ConsoleApp1.ServiceReference1.accountListRequest request) {
            return base.Channel.accountListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.accountListResponse> accountListAsync() {
            ConsoleApp1.ServiceReference1.accountListRequest inValue = new ConsoleApp1.ServiceReference1.accountListRequest();
            return ((ConsoleApp1.ServiceReference1.BanqueService)(this)).accountListAsync(inValue);
        }
    }
}
